[[project]]
name = "barreldb"
description = "A disk based KV store (based on Bitcask implementation)"
links = [
  { name = "Blog", url = "https://abhimanyusikarwar.com/posts/barreldb/" },
  { name = "GitHub", url="https://github.com/abhimanyu-sikarwar/barreldb" },
]
